# Generated by Django 3.1 on 2020-12-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
