# Generated by Django 3.1 on 2020-12-08 10:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_skill_skills_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skills_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
