# Generated by Django 3.1 on 2020-12-08 10:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20201208_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
